# Generated by Django 5.0.6 on 2024-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0002_book_genre_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="birthdate",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AddField(
            model_name="author",
            name="nationality",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
