# Generated by Django 5.0.6 on 2024-06-19 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0003_author_birthdate_author_nationality"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table="authors",
        ),
        migrations.AlterModelTable(
            name="book",
            table="books",
        ),
    ]
