# Generated by Django 5.0.6 on 2024-06-19 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0004_alter_author_table_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table="public.authors",
        ),
        migrations.AlterModelTable(
            name="book",
            table="public.books",
        ),
    ]
