# Generated by Django 5.0.6 on 2024-06-19 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0005_alter_author_table_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table="authors",
        ),
        migrations.AlterModelTable(
            name="book",
            table="books",
        ),
    ]
