# Generated by Django 5.0.6 on 2024-06-19 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0006_alter_author_table_alter_book_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "resources",
            },
        ),
        migrations.DeleteModel(
            name="NewModel",
        ),
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.RemoveField(
            model_name="video",
            name="description",
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="checkout_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="transaction",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="genre",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="video",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="video",
            name="publisher",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="video",
            name="release_date",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookstore.book",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookstore.video",
            ),
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="transactions",
        ),
        migrations.AlterModelTable(
            name="video",
            table="videos",
        ),
    ]
