# Generated by Django 5.0.6 on 2024-06-19 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0007_resources_delete_newmodel_remove_student_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="students",
        ),
    ]
